chore(ci-lighthouse) - Add lighthouse job in auto-deployments and manual-deployment pipeline

diff --git a/.github/workflows/manual-deployment.yml b/.github/workflows/manual-deployment.yml
--- a/.github/workflows/manual-deployment.yml
+++ b/.github/workflows/manual-deployment.yml
@@ -57,3 +57,23 @@ jobs:
         run: |
           cd packages/$SPA_NAME
           npx @spaship/cli@latest deploy --apikey=${{ secrets.SPASHIP_API_KEY }} --env=${{ secrets.SPASHIP_DEPLOY_URL }}${{ inputs.env }} --ref=$(node -p "require('./package.json').version")
+
+      - name: Get SPA NAME as strings
+        id: get-lighthouse-branch-name
+        if: contains(matrix.container, '-spa')
+        uses: actions/github-script@v6
+        with:
+          script: core.setOutput('LIGHTHOUSE_BRANCH_NAME', "$SPA_NAME".toUpperCase())
+
+      - name: Lighthouse CI
+        env:
+          NODE_TLS_REJECT_UNAUTHORIZED: 0
+          SSO_PASSWORD: ${{ secrets.SSO_PASSWORD }}
+          SSO_USERNAME: ${{ secrets.SSO_USERNAME }}
+          LH_HOST: ${{ secrets.LH_HOST }}
+          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ steps.get-lighthouse-branch-name.outputs.LIGHTHOUSE_BRANCH_NAME }}
+
+        run: |
+          cd packages/$SPA_NAME
+          npm i puppeteer
+          npx @lhci/cli@0.10.0 autorun --upload.serverBaseUrl=${{ secrets.SERVER_BASE_URL }} --upload.token=${{ secrets.LIGHTHOUSE_TOKEN }} || echo 'Lighthouse assert failed'
